#!/bin/sh

set -ex

sudo scutil --set HostName $(sudo scutil --get ComputerName)
sudo scutil --set LocalHostName $(sudo scutil --get ComputerName)

DIR=$(mktemp -d)

security export -t certs -f pemseq -k /System/Library/Keychains/SystemRootCertificates.keychain -o $DIR/bundle.pem
export SSL_CERT_FILE=$DIR/bundle.pem

nix build ".#darwinConfigurations.$(hostname).system" --extra-experimental-features "nix-command flakes" -o $DIR/result
$DIR/result/sw/bin/darwin-rebuild switch --flake .
